# Generated by Django 5.2.2 on 2025-06-04 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('beneficio_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Benefício Mensal (R$)')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Administrador?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('unidade_medida', models.CharField(blank=True, help_text='Ex: Kg, Unidade, Litro, Dúzia', max_length=50, null=True, verbose_name='Unidade de Medida')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ListaDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('aberta', 'Em Aberto'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status da Lista')),
                ('limite_compra_calculado', models.DecimalField(decimal_places=2, help_text='Limite da compra no momento da criação da lista (3x benefício mensal)', max_digits=10, verbose_name='Limite de Compra Calculado (R$)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_de_compra', to='feira_app.beneficiario', verbose_name='Beneficiário')),
            ],
            options={
                'verbose_name': 'Lista de Compra',
                'verbose_name_plural': 'Listas de Compra',
                'ordering': ['-data_criacao', 'beneficiario'],
            },
        ),
        migrations.CreateModel(
            name='ItemDaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario_no_momento', models.DecimalField(decimal_places=2, help_text='Preço do produto no momento em que foi adicionado à lista', max_digits=10, verbose_name='Preço Unitário no Momento da Compra (R$)')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_da_lista', to='feira_app.listadecompra', verbose_name='Lista de Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feira_app.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Lista',
                'verbose_name_plural': 'Itens da Lista',
                'ordering': ['produto__nome'],
                'unique_together': {('lista', 'produto')},
            },
        ),
    ]
